/// Markdown report header template.
pub const REPORT_HEADER: &str = r#"# AgentSpyBoo Penetration Test Report

**Generated by**: AgentSpyBoo v0.1.0 — AI Red Team Agent
**Date**: {date}
**Target**: {target}

---

## Executive Summary

{executive_summary}

## Severity Breakdown

| Severity | Count |
|----------|-------|
| Critical | {critical} |
| High     | {high} |
| Medium   | {medium} |
| Low      | {low} |
| Info     | {info} |
| **Total** | **{total}** |

---

## Findings

"#;

/// Template for an individual finding entry.
pub const FINDING_ENTRY: &str = r#"### {index}. [{severity}] {title}

- **Tool**: {tool}
- **Target**: {target}
- **Timestamp**: {timestamp}

**Description**:
{description}

**Evidence**:
```
{evidence}
```

---

"#;

/// Report footer.
pub const REPORT_FOOTER: &str = r#"
## Methodology

This assessment was conducted using AgentSpyBoo, an autonomous AI-driven penetration testing agent.
The agent follows a ReAct (Reason + Act) loop, progressing through phases:

1. **Reconnaissance** — Passive subdomain and URL discovery
2. **Enumeration** — Active service and port scanning
3. **Vulnerability Scanning** — Template-based vulnerability detection
4. **Exploitation** — Verification of exploitable conditions
5. **Reporting** — Automated finding compilation and severity rating

## Disclaimer

This report was generated by an automated tool. All findings should be verified manually before
taking remediation action. False positives are possible.

---
*AgentSpyBoo — AI Red Team Agent · AMD NPU Powered · Zero Cloud*
"#;
